service: public-toilets

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.10
  region: eu-west-1

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
    memorySize: 128
    timeout: 20
    cors:
      origin: '*'
      headers:
        - Content-Type

plugins:
  - serverless-wsgi
  - serverless-python-requirements
